cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z1.0_eta0.1/time.txt ./output_dip10_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z1.0_eta0.2/time.txt ./output_dip10_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z1.0_eta1.0/time.txt ./output_dip10_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z2.0_eta0.1/time.txt ./output_dip10_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z2.0_eta0.2/time.txt ./output_dip10_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z2.0_eta1.0/time.txt ./output_dip10_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z3.0_eta0.1/time.txt ./output_dip10_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z3.0_eta0.2/time.txt ./output_dip10_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip10_z3.0_eta1.0/time.txt ./output_dip10_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z1.0_eta0.1/time.txt ./output_dip20_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z1.0_eta0.2/time.txt ./output_dip20_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z1.0_eta1.0/time.txt ./output_dip20_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z2.0_eta0.1/time.txt ./output_dip20_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z2.0_eta0.2/time.txt ./output_dip20_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z2.0_eta1.0/time.txt ./output_dip20_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z3.0_eta0.1/time.txt ./output_dip20_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z3.0_eta0.2/time.txt ./output_dip20_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip20_z3.0_eta1.0/time.txt ./output_dip20_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z1.0_eta0.1/time.txt ./output_dip30_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z1.0_eta0.2/time.txt ./output_dip30_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z1.0_eta1.0/time.txt ./output_dip30_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z2.0_eta0.1/time.txt ./output_dip30_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z2.0_eta0.2/time.txt ./output_dip30_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z2.0_eta1.0/time.txt ./output_dip30_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z3.0_eta0.1/time.txt ./output_dip30_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z3.0_eta0.2/time.txt ./output_dip30_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip30_z3.0_eta1.0/time.txt ./output_dip30_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z1.0_eta0.1/time.txt ./output_dip40_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z1.0_eta0.2/time.txt ./output_dip40_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z1.0_eta1.0/time.txt ./output_dip40_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z2.0_eta0.1/time.txt ./output_dip40_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z2.0_eta0.2/time.txt ./output_dip40_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z2.0_eta1.0/time.txt ./output_dip40_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z3.0_eta0.1/time.txt ./output_dip40_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z3.0_eta0.2/time.txt ./output_dip40_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip40_z3.0_eta1.0/time.txt ./output_dip40_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z1.0_eta0.1/time.txt ./output_dip50_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z1.0_eta0.2/time.txt ./output_dip50_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z1.0_eta1.0/time.txt ./output_dip50_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z2.0_eta0.1/time.txt ./output_dip50_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z2.0_eta0.2/time.txt ./output_dip50_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z2.0_eta1.0/time.txt ./output_dip50_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z3.0_eta0.1/time.txt ./output_dip50_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z3.0_eta0.2/time.txt ./output_dip50_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip50_z3.0_eta1.0/time.txt ./output_dip50_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z1.0_eta0.1/time.txt ./output_dip60_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z1.0_eta0.2/time.txt ./output_dip60_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z1.0_eta1.0/time.txt ./output_dip60_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z2.0_eta0.1/time.txt ./output_dip60_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z2.0_eta0.2/time.txt ./output_dip60_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z2.0_eta1.0/time.txt ./output_dip60_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z3.0_eta0.1/time.txt ./output_dip60_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z3.0_eta0.2/time.txt ./output_dip60_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip60_z3.0_eta1.0/time.txt ./output_dip60_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z1.0_eta0.1/time.txt ./output_dip70_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z1.0_eta0.2/time.txt ./output_dip70_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z1.0_eta1.0/time.txt ./output_dip70_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z2.0_eta0.1/time.txt ./output_dip70_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z2.0_eta0.2/time.txt ./output_dip70_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z2.0_eta1.0/time.txt ./output_dip70_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z3.0_eta0.1/time.txt ./output_dip70_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z3.0_eta0.2/time.txt ./output_dip70_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip70_z3.0_eta1.0/time.txt ./output_dip70_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z1.0_eta0.1/time.txt ./output_dip80_z1.0_eta0.1/time.txt 
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z1.0_eta0.2/time.txt ./output_dip80_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z1.0_eta1.0/time.txt ./output_dip80_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z2.0_eta0.1/time.txt ./output_dip80_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z2.0_eta0.2/time.txt ./output_dip80_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z2.0_eta1.0/time.txt ./output_dip80_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z3.0_eta0.1/time.txt ./output_dip80_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z3.0_eta0.2/time.txt ./output_dip80_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip80_z3.0_eta1.0/time.txt ./output_dip80_z3.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z1.0_eta0.1/time.txt ./output_dip90_z1.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z1.0_eta0.2/time.txt ./output_dip90_z1.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z1.0_eta1.0/time.txt ./output_dip90_z1.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z2.0_eta0.1/time.txt ./output_dip90_z2.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z2.0_eta0.2/time.txt ./output_dip90_z2.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z2.0_eta1.0/time.txt ./output_dip90_z2.0_eta1.0/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z3.0_eta0.1/time.txt ./output_dip90_z3.0_eta0.1/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z3.0_eta0.2/time.txt ./output_dip90_z3.0_eta0.2/time.txt
cp /Volumes/jloveles/relax_bin/examples/tutorials/parameter_ranges/output_dip90_z3.0_eta1.0/time.txt ./output_dip90_z3.0_eta1.0/time.txt